#!/bin/sh /etc/rc.common

START=10
SDCARD=/dev/mmcblk0
DOCKERPART=${SDCARD}p3

boot() {
    # docker partition
    [ -b ${DOCKERPART} ] || return 0
    uci -q get fstab.docker.uuid && return 0
    
    FSUUID=$(lsblk --noheadings -o UUID ${DOCKERPART})

    if [ -z "${FSUUID}" ]; then
        logger -p info -t mkpart 'Create F2FS filesystem on DOCKER partition'
        mkfs.f2fs -l DOCKER -O 'extra_attr,inode_checksum,sb_checksum' -q ${DOCKERPART} | logger -t mkpart -s
        FSUUID=$(lsblk --noheadings -o UUID ${DOCKERPART})
        if [ -z "${FSUUID}" ]; then
            logger -p err -t mkpart -s 'Failed to create F2FS filesystem on DOCKER partition'
            return 0
        fi
    fi
    
    uci -q batch << EOF
set fstab.@mount[-1].uuid=${FSUUID}
set fstab.@mount[-1].target=/opt/docker
set fstab.@mount[-1].options=atgc
set fstab.@mount[-1].enabled=1
rename fstab.@mount[-1]=docker
commit fstab
EOF
}

